### ISSUE TITLE
Cannot run/compile

### ISSUE THREAD

**Issue by hasan1292** [shawn615/FlipNeRF#1]
I followed all the instructions you gave to install, and after doing this, it throws error no cannot import flax error. When I install flax, it throws errors like mismatch of the settings. when I finally figure them out. It throws this error:
    from jax.nn.initializers import constant
ImportError: cannot import name 'constant'

Can you please re-create the environment and check if it is working flawlessly on your side? Because I think you created an environment long ago and now when we try to recreate it, it throws tons of errors.

**Comment by shawn615** [comment]
I appreciate your interest in our paper and am sorry for the late reply! :(

On my side, I can run the code without the error that you mentioned.
I checked the installed library versions, and it's all the same as those in the requirements.txt.
I've also seen errors like the one you bumped into, and it was usually the mismatch of the versions between flax, jax, or jaxlib.

I suggest you check and adjust the related libraries' versions; please let me know if it still does not work. :)
