### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by hasan1292** [shawn615/FlipNeRF#2]
Hi, 

I successfully trained and tested llff3.gin 

Now I used this command "python render.py --gin_configs configs/llff3.gin

But all I get is lots of tiff files. Shouldn't I get a rendered video? Please help

**Comment by shawn615** [comment]
Sorry for the late reply.
I've been busy attending to the ICCV :(

For the video, I made it with the simple code of making a video file with output images.
Kindly refer to [nerf-pytorch github](https://github.com/yenchenlin/nerf-pytorch) as an example, but you can just use your own code of course :)
If the tiff format is your problem, you can get the depth files in png format as well like rgbs in our code.
I hope it helps.

Thanks.
