### ISSUE TITLE
Negative loss function value and  gradient explosion

### ISSUE THREAD

**Issue by WangPost** [shawn615/FlipNeRF#3]
Thank you for your great work. 
I Reproduce your work. I found negative loss function value and gradient explosion.

![`KKUZF7MBCG47I}_5TO%YRJ](https://github.com/shawn615/FlipNeRF/assets/108411321/04634007-8704-46fd-84f0-61ca2448e4ba)

![UJ@ PRK$ZEG%QSQ3Z%AOXGO](https://github.com/shawn615/FlipNeRF/assets/108411321/48677260-2819-42a5-a7fd-e2a25a38e4d4)

**Comment by shawn615** [comment]
Thanks for your interest in our paper.

It sometimes occurs due to the log and exp function in the loss terms for mixture modeling.
Adding "Config.check_grad_for_nans = True" in the config file will prevent the explosion.

I hope it helps. :)
