### ISSUE TITLE
the normals directions

### ISSUE THREAD

**Issue by whalien-902** [shawn615/FlipNeRF#4]
Is the normal direction derived from the nerf an NDC space or an OpenGL coordinate system?Whether the normal direction needs to be transformed

**Comment by shawn615** [comment]
Thanks for your interest in our paper.

The normal vector used in NeRF is negative normalized gradient derived from the density, and as far as I know, the concept in the surface normals is not commonly used in NDC space.

**Comment by whalien-902** [comment]
Thanks for your answer, I see you train the llff dataset in NDC space, you calculate the normal vector by negative normalized gradient derived from the density. So whether the normal vector direction is calculated in ndc space or opengl space

**Comment by shawn615** [comment]
Yes, just to implement it as simple as we can, we do not convert the normal vector into the opengl space explicitly, but just use it in ndc space for the LLFF dataset.
If it is derived in the opengl space and then converted into ndc space, like the case of llff dataset, maybe we can see some meaningful differences but we have to try :)

**Comment by whalien-902** [comment]
Thanks for your answer
